apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: www-esky-pl
  namespace: frontend
spec:
  hosts:
    - www.esky.pl
  exportTo:
    - "."
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
